spring.application.name=ecommerce
# it is for out system
# spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
#when we delaing with docker container
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9090